# Generated by Django 4.2.24 on 2025-10-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_agent_code_user_commission_percent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission_percent',
        ),
        migrations.AddField(
            model_name='user',
            name='currency_preference',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('SYP', 'Syrian Pound')], default='USD', max_length=3),
        ),
    ]
