# Generated by Django 4.2.24 on 2025-10-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(default='Payment', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentMethodField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_key', models.SlugField(max_length=255)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('file', 'File')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='payment_methods.paymentmethod')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
