# Generated by Django 4.2.24 on 2025-10-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_externalproduct_alter_product_options_and_more'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('text_color', models.CharField(choices=[('white', 'أبيض'), ('black', 'أسود')], default='black', max_length=5)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads_images/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.product')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='store.section')),
            ],
        ),
    ]
