# Generated by Django 4.2.24 on 2025-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agentproductassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
