# Generated by Django 4.2.24 on 2025-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('syp', 'Syrian Pound')], max_length=10)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('account_details', models.TextField()),
                ('instructions', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
