# Generated by Django 4.2.25 on 2025-10-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartyapi',
            name='provider',
            field=models.CharField(choices=[('daily', 'Daily'), ('alfaour', 'Alfaour'), ('alaaeddin', 'Alaaeddin')], max_length=50),
        ),
    ]
