# Generated by Django 4.2.24 on 2025-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('usd', 'US Dollar'), ('syp', 'Syrian Pound')], max_length=10),
        ),
    ]
