# Generated by Django 4.2.24 on 2025-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='syp_to_usd',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='usd_to_syp',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
