# Generated by Django 4.2.25 on 2025-10-11 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('third_party_apis', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name_en']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['name_en']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='max_value',
            new_name='max_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='min_value',
            new_name='min_amount',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='product',
            name='api_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='third_party_apis.thirdpartyapi'),
        ),
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='customization_options',
            field=models.TextField(blank=True, help_text='Comma-separated values: option1,option2,option3', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_prices',
            field=models.TextField(blank=True, help_text='Comma-separated prices matching options: 10,15,20', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_amount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for the minimum amount (will be used to calculate price per unit)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(default='Product Name EN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Automatically calculated: min_amount_price / min_amount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='section',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='father_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='store.section'),
        ),
        migrations.AddField(
            model_name='section',
            name='name_en',
            field=models.CharField(default='Section Name EN', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('amount_based', 'Amount Based'), ('customization_based', 'Customization Based')], default='amount_based', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('id', 'ID')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
