# Generated by Django 4.2.24 on 2025-09-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('usd', 'US Dollar'), ('syp', 'Syrian Pound')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='store.package')),
            ],
            options={
                'unique_together': {('package', 'currency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='payment_method',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='store.product'),
        ),
    ]
